### ISSUE TITLE
SVC' object has no attribute 'n_binary_model'

### ISSUE THREAD

**Issue by pardedetalenta** [zeyiwen/thundersvm#93]
I got error when i want to use ypred=clf.decision_function(xtest). 

2018-07-12 07:40:56 PSTFile "/usr/local/lib/python3.6/site-packages/thundersvm-github_master-py3.6.egg/thundersvmScikit.py", line 290, in decision_function
2018-07-12 07:40:56 PSTdec_func = self._dense_decision_function(X)
2018-07-12 07:40:56 PSTFile "/usr/local/lib/python3.6/site-packages/thundersvm-github_master-py3.6.egg/thundersvmScikit.py", line 301, in _dense_decision_function
2018-07-12 07:40:56 PSTdec_size = X.shape[0] * self.n_binary_model
2018-07-12 07:40:56 PSTAttributeError: 'SVC' object has no attribute 'n_binary_model'

What's wrong?

**Comment by GODqinbin** [comment]
Did you use clf.fit() before clf.decision_function()?

**Comment by pardedetalenta** [comment]
I load model i've fit before and use it to this decision_function

clf = SVC()
clf.load_from_file('/my-model/svm.model')
ypred=clf.decision_function(xtest)

**Comment by GODqinbin** [comment]
Thanks for your feedback! We have fixed the bug. You can try again.

**Comment by pardedetalenta** [comment]
I still have the error?

what(): std::bad_alloc
2018-07-12 07:40:56 PSTFile "/usr/local/lib/python3.6/site-packages/thundersvm-github_master-py3.6.egg/thundersvmScikit.py", line 290, in decision_function
Aborted (core dumped)

################################################################################
dec_func = self._dense_decision_function(X)
Waiting for container to complete...
File "/usr/local/lib/python3.6/site-packages/thundersvm-github_master-py3.6.egg/thundersvmScikit.py", line 301, in _dense_decision_function
Job exited with status code: 134
Creating data module for output...
Data module created for output.
dec_size = X.shape[0] * self.n_binary_model
Persisting data in home...
Error: 'SVC' object has no attribute 'n_binary_model'

**Comment by GODqinbin** [comment]
Did you use the latest code? It seems you install thundersvm as a python library. You need to run `python setup.py install` again in python directory to update the system library.

**Comment by pardedetalenta** [comment]
Thank you @GODqinbin , I have a little problem with std::bad_alloc. Can I do reduce the amount of memory used in my code? Or any advice to solve my problem? Thank you :)

**Comment by GODqinbin** [comment]
You can use the "max_mem_size" parameter to set the maximum memory size (MB) that thundersvm uses. You can refer to the document.

**Comment by pardedetalenta** [comment]
Should i fit with max_mem_size again or i can use my loaded model and make it SVC(max_mem_size)?

**Comment by pardedetalenta** [comment]
it keep return the error even when i use max_mem_size 
FATAL [default] Check failed: [error == cudaSuccess] an illegal memory access was encountered
INFO [default] global iter = 100, total local iter = 13618, diff = 3.01517
WARNING [default] Aborting application. Reason: Fatal log at [/floyd/home/thundersvm/src/thundersvm/syncmem.cpp:29]
INFO [default] global iter = 200, total local iter = 26867, diff = 3.11846
Aborted (core dumped)

**Comment by GODqinbin** [comment]
Can you share the dataset and the commands you used? So we can reproduce the problem and debug.

**Comment by pardedetalenta** [comment]
Here : https://drive.google.com/open?id=1jQuHW1tJvSvuyEHip1CrUKackkJEOrms I've attached my code and my command.

Thank you

**Comment by GODqinbin** [comment]
We have fixed a bug on max_mem_size parameter. I can train your dataset successfully after change `clf = SVC(C=0.1, gamma =0.01, max_mem_size=12000, verbose=True)` to `clf = SVC(C=0.1, gamma =0.01, max_mem_size=8192, verbose=True)`. You can update the codes and try again. Remember, the max_mem_size parameter sets the maximum memory size (MB) that gpu uses. You can change the max_mem_size to a smaller size if your gpu's memory is not big enough.

**Comment by pardedetalenta** [comment]
Thank you @GODqinbin

**Comment by pardedetalenta** [comment]
I think there's problem in decision_function. It keeps giving me error core dump every time I want to use it.  Even when I decrease the max_mem_size it also gives the error. Actualy I want to use decion_function on roc_auc_score, but it keeps giving the error. What's wrong?

**Comment by GODqinbin** [comment]
The predict batch size may be too big in decision_function. We have fixed the problem. Now I can run the decision_function successfully for your dataset. You can update the library and try again.

**Comment by pardedetalenta** [comment]
Thank you @GODqinbin , I've tried it and run it successfully 👍 And I have very low roc_auc_score, I run my code and sampling my dataset randomly with sklearn SVC I got high roc_auc_score based on decision_function and predict_proba. Is it possible that the score I got has a very large difference roc_auc_score because I sampling it? Or decision_function on thundersvm have a different concept about decision_function?
Please help me, and sorry I'm very new in this field.  Once again thank you @GODqinbin

**Comment by GODqinbin** [comment]
The decision values returned by decision_function in ThunderSVM are computed differently from libsvm in sklearn.  However, they both reflect the distance to the separating hyperplane. I'm not familiar with roc_auc_score and I don't know if it's ok to input the decision_function. We just implemented the predict_proba() function. I tried `roc_auc_score(ytest, clf.predict_proba(xtest)[:,1])` and got 0.682. You can update the library and have a try. Additionally, predict_proba() can only be used in models that fit() with probability = True. Thanks.
